"""
Generated by data_migration 0.0.1a

File: 0002_auto.py
Created: 2021-05-22 11:23
"""
from tests.unittests.services.test_graph import set_some_value


class Node:
    name = '0002_auto'
    dependencies = ('0001_first', )
    migration_dependencies = ()
    routines = [
        set_some_value
    ]
