"""
Generated by data_migration 0.0.1a

File: 0001_0002_split_name.py
Created: 2021-06-11 20:14
"""

import importlib.util
spec = importlib.util.spec_from_file_location("tests.unittests.test_app_2.migrations.0002_split_name", "tests/unittests/test_app_2/migrations/0002_split_name.py")
mig_0002_split_name = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mig_0002_split_name)


class Node:
    name = '0001_0002_split_name'
    dependencies = ()
    migration_dependencies = ('tests.unittests.test_app_2.0002_split_name', 'test_app_2.0008_customer_is_business', )
    routines = [
		mig_0002_split_name.split_name,
	]
