"""
Generated by data_migration 0.0.1a

File: 0002_0006_address_line_split.py
Created: 2021-06-11 20:14
"""

import importlib.util
spec = importlib.util.spec_from_file_location("tests.unittests.test_app_2.migrations.0006_address_line_split", "tests/unittests/test_app_2/migrations/0006_address_line_split.py")
mig_0006_address_line_split = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mig_0006_address_line_split)


class Node:
    name = '0002_0006_address_line_split'
    dependencies = ('0001_0002_split_name', )
    migration_dependencies = ('tests.unittests.test_app_2.0006_address_line_split', 'test_app_2.0008_customer_is_business', )
    routines = [
		mig_0006_address_line_split.move_data_forward,
	]
