# Generated by Django 3.2 on 2021-05-24 09:19

from django.db import migrations, models


def split_name(apps, schema_editor):
    some_class = apps.get_model('test_app_2', 'SomeClass')
    qs = some_class.objects.all()
    for obj in qs:
        if len(obj.name) >= 1:
            obj.first_name = obj.name[0]
        if len(obj.name) == 2:
            obj.last_name = obj.name[1]


def combine_name(apps, schema_editor):
    some_class = apps.get_model('test_app_2', 'SomeClass')
    some_class.objects.all().update(
        name=models.F('first_name') + models.F('last_name')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('test_app_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='someclass',
            name='first_name',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='someclass',
            name='last_name',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.RunPython(
            split_name,
            combine_name
        ),
        migrations.RemoveField(
            model_name='someclass',
            name='name',
        ),
    ]
