# Generated by Django 3.2 on 2021-05-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app_2', '0002_split_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit', models.BooleanField()),
                ('name', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
