# Generated by Django 3.2 on 2021-05-24 14:49

from django.db import migrations, models


def move_data_forward(apps, schema_editor):
    some_class = apps.get_model('test_app_2', 'Customer')
    some_class.objects.filter(address__isnull=False).update(address_line_1=models.F('address'))


def move_data_back(apps, schema_editor):
    some_class = apps.get_model('test_app_2', 'Customer')
    some_class.objects.filter(address_line_1__isnull=False).update(address=models.F('address_line_1'))


class Migration(migrations.Migration):

    dependencies = [
        ('test_app_2', '0005_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(
            move_data_forward, move_data_back
        )
    ]
